package elmt
// This file is generated by buildElementTable in builder.go

const (
	ZΩ Symbol = iota
	Aα
	Bα
	Cα
	Dα
	Eα
	Fα
	Gα
	Hα
	Iα
	Jα
	Kα
	Lα
	Mα
	Nα
	Oα
	Pα
	Aβ
	Bβ
	Cβ
	Dβ
	Eβ
	Fβ
	Gβ
	Hβ
	Iβ
	Jβ
	Kβ
	Lβ
	Mβ
	Nβ
	Oβ
	Pβ
)

var eTable = [...]Atom{
	{symbol: ZΩ,	name: "Z.Omega",	short: "ZΩ",	energy:  0,	links: 0,	polarity:  0,	decay: ZΩ},
	{symbol: Aα,	name: "A.Alpha",	short: "Aα",	energy:  1,	links: 1,	polarity:  1,	decay: Aα},
	{symbol: Bα,	name: "B.Alpha",	short: "Bα",	energy:  2,	links: 2,	polarity: -1,	decay: Bα},
	{symbol: Cα,	name: "C.Alpha",	short: "Cα",	energy:  3,	links: 0,	polarity:  0,	decay: Cα},
	{symbol: Dα,	name: "D.Alpha",	short: "Dα",	energy:  4,	links: 0,	polarity:  0,	decay: Cα},
	{symbol: Eα,	name: "E.Alpha",	short: "Eα",	energy:  5,	links: 1,	polarity:  1,	decay: Aα},
	{symbol: Fα,	name: "F.Alpha",	short: "Fα",	energy:  6,	links: 2,	polarity: -1,	decay: Bα},
	{symbol: Gα,	name: "G.Alpha",	short: "Gα",	energy:  7,	links: 3,	polarity: -2,	decay: Gα},
	{symbol: Hα,	name: "H.Alpha",	short: "Hα",	energy:  8,	links: 0,	polarity:  0,	decay: Dα},
	{symbol: Iα,	name: "I.Alpha",	short: "Iα",	energy:  9,	links: 0,	polarity:  0,	decay: Hα},
	{symbol: Jα,	name: "J.Alpha",	short: "Jα",	energy: 10,	links: 1,	polarity:  1,	decay: Eα},
	{symbol: Kα,	name: "K.Alpha",	short: "Kα",	energy: 11,	links: 2,	polarity: -1,	decay: Fα},
	{symbol: Lα,	name: "L.Alpha",	short: "Lα",	energy: 12,	links: 3,	polarity: -2,	decay: Gα},
	{symbol: Mα,	name: "M.Alpha",	short: "Mα",	energy: 13,	links: 4,	polarity: -1,	decay: Mα},
	{symbol: Nα,	name: "N.Alpha",	short: "Nα",	energy: 14,	links: 0,	polarity:  0,	decay: Iα},
	{symbol: Oα,	name: "O.Alpha",	short: "Oα",	energy: 15,	links: 1,	polarity:  1,	decay: Jα},
	{symbol: Pα,	name: "P.Alpha",	short: "Pα",	energy: 16,	links: 2,	polarity: -1,	decay: Kα},
	{symbol: Aβ,	name: "A.Beta", 	short: "Aβ",	energy: 17,	links: 3,	polarity: -2,	decay: Lα},
	{symbol: Bβ,	name: "B.Beta", 	short: "Bβ",	energy: 18,	links: 4,	polarity: -1,	decay: Mα},
	{symbol: Cβ,	name: "C.Beta", 	short: "Cβ",	energy: 19,	links: 5,	polarity: -2,	decay: Cβ},
	{symbol: Dβ,	name: "D.Beta", 	short: "Dβ",	energy: 20,	links: 6,	polarity:  2,	decay: Dβ},
	{symbol: Eβ,	name: "E.Beta", 	short: "Eβ",	energy: 21,	links: 7,	polarity:  3,	decay: Eβ},
	{symbol: Fβ,	name: "F.Beta", 	short: "Fβ",	energy: 22,	links: 8,	polarity: -1,	decay: Fβ},
	{symbol: Gβ,	name: "G.Beta", 	short: "Gβ",	energy: 23,	links: 0,	polarity:  0,	decay: Nα},
	{symbol: Hβ,	name: "H.Beta", 	short: "Hβ",	energy: 24,	links: 1,	polarity:  1,	decay: Oα},
	{symbol: Iβ,	name: "I.Beta", 	short: "Iβ",	energy: 25,	links: 0,	polarity:  0,	decay: Gβ},
	{symbol: Jβ,	name: "J.Beta", 	short: "Jβ",	energy: 26,	links: 1,	polarity:  1,	decay: Hβ},
	{symbol: Kβ,	name: "K.Beta", 	short: "Kβ",	energy: 27,	links: 2,	polarity: -1,	decay: Pα},
	{symbol: Lβ,	name: "L.Beta", 	short: "Lβ",	energy: 28,	links: 3,	polarity: -2,	decay: Aβ},
	{symbol: Mβ,	name: "M.Beta", 	short: "Mβ",	energy: 29,	links: 4,	polarity: -1,	decay: Bβ},
	{symbol: Nβ,	name: "N.Beta", 	short: "Nβ",	energy: 30,	links: 5,	polarity: -2,	decay: Cβ},
	{symbol: Oβ,	name: "O.Beta", 	short: "Oβ",	energy: 31,	links: 0,	polarity:  0,	decay: Iβ},
	{symbol: Pβ,	name: "P.Beta", 	short: "Pβ",	energy: 32,	links: 1,	polarity:  1,	decay: Jβ},
}
